name: Publish Blog

on:
  push:
    branches:
      - master  # master 分支 push 後觸發腳本

jobs:
  deploy:
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1' # hugo 版本，也可以用 latest
          # extended: true

      # Blonde 樣板有使用 postcss ，所以要先建立 npm 環境並加入相關套件
      - name: Setup Node
        uses: actions/setup-node@v2 
        with:
          node-version: '14'

      - name: Setup PostCSS
        run: npm install -g postcss-cli autoprefixer postcss
 
      - name: Setup Theme Dependency
        run: npm install --prefix themes/Blonde --production=false 

      # 用 Hugo 編譯靜態檔案，使用 production config
      - name: Build
        run: hugo --minify  
        env:          
          HUGO_disqusShortname: ${{ secrets.DISQUS_SHORT_NAME }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages  # 推送到 gh-pages 分支
          PUBLISH_DIR: ./public     # hugo 生成的目錄
          commit_message: ${{ github.event.head_commit.message }}
